from __future__ import annotations

from datetime import timedelta

DOMAIN = "ha_evctrl"
CONF_WS_URL = "websocket_url"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_RECONNECT_INTERVAL = "reconnect_interval"
CONF_SENSOR_PREFIX = "sensor_prefix"
CONF_PAYLOAD_LOG_LEVEL = "payload_log_level"

PAYLOAD_LOG_LEVEL_OFF = "off"
PAYLOAD_LOG_LEVEL_INFO = "info"
PAYLOAD_LOG_LEVEL_DEBUG = "debug"
PAYLOAD_LOG_LEVEL_OPTIONS = (
    PAYLOAD_LOG_LEVEL_OFF,
    PAYLOAD_LOG_LEVEL_INFO,
    PAYLOAD_LOG_LEVEL_DEBUG,
)

DEFAULT_RECONNECT_INTERVAL = 15
STREAM_INACTIVITY_TIMEOUT = 120
STREAM_NOTIFICATION_TIMEOUT = 300
DEFAULT_SENSOR_PREFIX = "EV Control"
DEFAULT_PAYLOAD_LOG_LEVEL = PAYLOAD_LOG_LEVEL_OFF

UPDATE_COOLDOWN = timedelta(seconds=1)
